### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by HelloXMFJ** [smthemex/ComfyUI_OmniParser#5]
Prompt executed in 144.56 seconds
got prompt
Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
!!! Exception during processing !!! Remote end closed connection without response
Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "s/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/square/bitsandbytes/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/square/bitsandbytes/ComfyUI/custom_nodes/ComfyUI_OmniParser/OmniParser_node.py", line 117, in main
    ORC = easyocr.Reader([orc_mode])
  File "/miniconda3/envs/comfyui/lib/python3.10/site-packages/easyocr/easyocr.py", line 178, in __init__
    download_and_unzip(model['url'], model['filename'], self.model_storage_directory, verbose)
  File "/miniconda3/envs/comfyui/lib/python3.10/site-packages/easyocr/utils.py", line 628, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

Prompt executed in 11.00 seconds

**Comment by smthemex** [comment]
check your net，easyocr需要连外网下载一个小模型
